[package]
name = "noiseexplorer_xpsk1"
version = "0.1.1"
authors = ["Georgio Nicolas <georgio@symbolic.software>"]
edition = "2018"

[dependencies]
blake2-rfc = "0.2.18"
rust-crypto = "0.2.36"
hacl-star = ">=0.0.14"
hex = ">=0.3.2"
rand = ">=0.6.5"
zeroize = ">=0.6.0"