indent_style = "Block"
use_small_heuristics = "Off"
binop_separator = "Front"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
disable_all_formatting = false
error_on_line_overflow = false
fn_args_density = "Compressed"
brace_style = "PreferSameLine"
empty_item_single_line = true
enum_discrim_align_threshold = 20
fn_single_line = false
where_single_line = true
force_explicit_abi = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = true
imports_indent = "Visual"
imports_layout = "Mixed"
merge_imports = true
match_block_trailing_comma = true
max_width = 100
merge_derives = true
force_multiline_blocks = false
newline_style = "Native"
#normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
report_todo = "Always"
report_fixme = "Always"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 20
spaces_around_ranges = false
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Always"
trailing_semicolon = true
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
wrap_comments = true
match_arm_blocks = false
overflow_delimited_expr = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
#required_version = "CARGO_PKG_VERSION"
hide_parse_errors = false
color = "Auto"
unstable_features = true
#license_template_path = ""
#ignore = []
edition = "2018"
version = "Two"
normalize_doc_attributes = true
inline_attribute_width = 0